### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by OwnyOne** [a1640727878/Live2D_Cubism_Crack#2]
When opening the bat it says "The system cannot find the path specified." then closes when pressing any key. I've run it as asministrator and it's the same, what should I do?

**Comment by a1640727878** [comment]
fix
![PZ1IT0584@R$}ED2LF_HDAB](https://github.com/a1640727878/Live2D_Cubism_Crack/assets/29010620/f058274d-4a22-4a4a-a1f2-afd8902d4a75)
